// VERDIQO BAIL MANAGEMENT SYSTEM - PILOT DATABASE
// Generated for Google Antigravity web app development
// Use: import { db } from './verdiqo_db.js'

export const db = {
  "bailApplications": [
    {
      "caseNo": "BMS/2026/0042",
      "firNo": "FIR/148/2026-RJM",
      "courtName": "Sessions Court Room 2",
      "district": "East Godavari",
      "psIoName": "SI Ravi Kumar",
      "arrestDate": "2026-04-10",
      "filingDate": "2026-05-01",
      "hearingDate": "2026-05-29",
      "hearingTime": "10:30",
      "bailType": "First Bail",
      "ipcBnsSections": "IPC 420, 468",
      "offenceCategory": "Financial Fraud",
      "proposedBailAmtRs": "50000",
      "accusedName": "Srinivas Rao Vemuri",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Flight risk possible",
      "defenceArgument": "Accused cooperative; items recovered; no flight risk",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "GRANTED",
      "aiRiskScore0100": "0",
      "systemRecommendation": "ACCEPT",
      "adjudication": "BAIL GRANTED"
    },
    {
      "caseNo": "BMS/2026/0040",
      "firNo": "FIR/133/2026-RJM",
      "courtName": "Sessions Court Room 2",
      "district": "East Godavari",
      "psIoName": "SI Lakshmi Devi",
      "arrestDate": "2026-04-02",
      "filingDate": "2026-04-20",
      "hearingDate": "2026-05-15",
      "hearingTime": "09:00",
      "bailType": "First Bail",
      "ipcBnsSections": "IPC 302",
      "offenceCategory": "Murder",
      "proposedBailAmtRs": "100000",
      "accusedName": "Anita Rao",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Serious offence; public danger",
      "defenceArgument": "Accused has no prior record; sole breadwinner",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "DENIED",
      "aiRiskScore0100": "95",
      "systemRecommendation": "REJECT",
      "adjudication": "BAIL DENIED â€“ REMAND"
    },
    {
      "caseNo": "BMS/2026/0043",
      "firNo": "FIR/152/2026-RJM",
      "courtName": "Sessions Court Room 1",
      "district": "East Godavari",
      "psIoName": "SI Mohan Rao",
      "arrestDate": "2026-04-12",
      "filingDate": "2026-05-03",
      "hearingDate": "2026-05-30",
      "hearingTime": "11:00",
      "bailType": "Anticipatory",
      "ipcBnsSections": "IPC 379, 411",
      "offenceCategory": "Theft / Receiving",
      "proposedBailAmtRs": "75000",
      "accusedName": "Priya Nair",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Prior absconding concern",
      "defenceArgument": "Recovery complete; stable employment",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "PENDING",
      "aiRiskScore0100": "42",
      "systemRecommendation": "CONDITIONAL ACCEPT",
      "adjudication": "UNDER REVIEW"
    },
    {
      "caseNo": "BMS/2026/0044",
      "firNo": "FIR/160/2026-RJM",
      "courtName": "Magistrate Court 3",
      "district": "East Godavari",
      "psIoName": "SI Venkat",
      "arrestDate": "2026-04-15",
      "filingDate": "2026-05-05",
      "hearingDate": "2026-05-30",
      "hearingTime": "11:30",
      "bailType": "Second Bail",
      "ipcBnsSections": "IPC 420, 406",
      "offenceCategory": "Cheating / CBT",
      "proposedBailAmtRs": "80000",
      "accusedName": "Ramesh Yadav",
      "judgeName": "J. Padma Rao",
      "ppObjection": "Surety overloaded",
      "defenceArgument": "Strong community ties; prior bail honoured",
      "previousBailRejected": "Yes",
      "previousRejectionDate": "2026-03-20",
      "rejectionReason": "Jurisdictional limitation",
      "applicationStatus": "CHECKING",
      "aiRiskScore0100": "60",
      "systemRecommendation": "CONDITIONAL ACCEPT",
      "adjudication": "AWAITING SURETY CLEAR"
    },
    {
      "caseNo": "BMS/2026/0045",
      "firNo": "FIR/171/2026-RJM",
      "courtName": "Sessions Court Room 2",
      "district": "East Godavari",
      "psIoName": "SI Praveen",
      "arrestDate": "2026-04-18",
      "filingDate": "2026-05-07",
      "hearingDate": "2026-05-31",
      "hearingTime": "09:30",
      "bailType": "First Bail",
      "ipcBnsSections": "IPC 302, 307",
      "offenceCategory": "Attempt to Murder",
      "proposedBailAmtRs": "150000",
      "accusedName": "Kavya Sharma",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Violent offence; witness tampering risk",
      "defenceArgument": "No prior record; family obligations",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "ALERT",
      "aiRiskScore0100": "88",
      "systemRecommendation": "REJECT",
      "adjudication": "DENIED â€“ HIGH RISK"
    },
    {
      "caseNo": "BMS/2026/0046",
      "firNo": "FIR/182/2026-RJM",
      "courtName": "Sessions Court Room 1",
      "district": "East Godavari",
      "psIoName": "SI Annapurna",
      "arrestDate": "2026-04-20",
      "filingDate": "2026-05-09",
      "hearingDate": "2026-06-01",
      "hearingTime": "10:00",
      "bailType": "Anticipatory",
      "ipcBnsSections": "IPC 409, 468",
      "offenceCategory": "Criminal Breach / Forgery",
      "proposedBailAmtRs": "60000",
      "accusedName": "Srinivas Reddy",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Documents tampered",
      "defenceArgument": "Accused surrendered; documents produced",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "CHECKING",
      "aiRiskScore0100": "35",
      "systemRecommendation": "ACCEPT",
      "adjudication": "PENDING VERIFICATION"
    },
    {
      "caseNo": "BMS/2026/0047",
      "firNo": "FIR/193/2026-RJM",
      "courtName": "Sessions Court Room 2",
      "district": "East Godavari",
      "psIoName": "SI Kishore",
      "arrestDate": "2026-04-22",
      "filingDate": "2026-05-11",
      "hearingDate": "2026-06-02",
      "hearingTime": "14:00",
      "bailType": "First Bail",
      "ipcBnsSections": "IPC 376",
      "offenceCategory": "Sexual Offence",
      "proposedBailAmtRs": "200000",
      "accusedName": "Vijay Santi",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Non-bailable serious offence",
      "defenceArgument": "â€“",
      "previousBailRejected": "Yes",
      "previousRejectionDate": "2026-04-30",
      "rejectionReason": "Magistrate lacked jurisdiction",
      "applicationStatus": "ALERT",
      "aiRiskScore0100": "100",
      "systemRecommendation": "REJECT",
      "adjudication": "DENIED â€“ LOC ACTIVE"
    },
    {
      "caseNo": "BMS/2026/0048",
      "firNo": "FIR/205/2026-RJM",
      "courtName": "Sessions Court Room 2",
      "district": "East Godavari",
      "psIoName": "SI Nagaraju",
      "arrestDate": "2026-04-25",
      "filingDate": "2026-05-13",
      "hearingDate": "2026-06-08",
      "hearingTime": "09:00",
      "bailType": "Anticipatory",
      "ipcBnsSections": "IPC 498A, 307",
      "offenceCategory": "Dowry / Attempt to Murder",
      "proposedBailAmtRs": "70000",
      "accusedName": "Krishnam Raju",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Multiple FIRs; surety disqualified",
      "defenceArgument": "Accused willing to cooperate",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "ALERT",
      "aiRiskScore0100": "100",
      "systemRecommendation": "REJECT",
      "adjudication": "DENIED â€“ SURETY DISQUALIFIED"
    },
    {
      "caseNo": "BMS/2026/0065",
      "firNo": "FIR/648/2026-RJM",
      "courtName": "Magistrate Court 1",
      "district": "East Godavari",
      "psIoName": "SI Bharath",
      "arrestDate": "2026-05-10",
      "filingDate": "2026-05-20",
      "hearingDate": "2026-06-05",
      "hearingTime": "10:30",
      "bailType": "First Bail",
      "ipcBnsSections": "IPC 420, 468",
      "offenceCategory": "Financial Fraud",
      "proposedBailAmtRs": "50000",
      "accusedName": "Ravi Teja Kommuri",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Young first offender; risk low",
      "defenceArgument": "Student; no criminal history",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "CHECKING",
      "aiRiskScore0100": "28",
      "systemRecommendation": "ACCEPT",
      "adjudication": "PENDING BIOMETRIC"
    },
    {
      "caseNo": "SC/98/2025",
      "firNo": "FIR/241/2025-RJM",
      "courtName": "Sessions Court Room 2",
      "district": "East Godavari",
      "psIoName": "SI Suresh",
      "arrestDate": "2025-11-05",
      "filingDate": "2025-11-20",
      "hearingDate": "2025-12-10",
      "hearingTime": "11:00",
      "bailType": "Second Bail",
      "ipcBnsSections": "IPC 411, 379",
      "offenceCategory": "Theft / Receiving Stolen",
      "proposedBailAmtRs": "90000",
      "accusedName": "R. K. Naidu",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "High risk profile; 3 FIRs; absconded prior",
      "defenceArgument": "â€“",
      "previousBailRejected": "Yes",
      "previousRejectionDate": "2025-10-01",
      "rejectionReason": "Prior absconding; high risk",
      "applicationStatus": "DENIED",
      "aiRiskScore0100": "100",
      "systemRecommendation": "REJECT",
      "adjudication": "DENIED â€“ IMMEDIATE REMAND"
    },
    {
      "caseNo": "SC/142/2024",
      "firNo": "FIR/142/2024-RJM",
      "courtName": "Sub-Court 1",
      "district": "East Godavari",
      "psIoName": "SI Devi Prasad",
      "arrestDate": "2024-08-01",
      "filingDate": "2024-08-15",
      "hearingDate": "2024-09-05",
      "hearingTime": "10:00",
      "bailType": "First Bail",
      "ipcBnsSections": "IPC 420",
      "offenceCategory": "Cheating",
      "proposedBailAmtRs": "40000",
      "accusedName": "Venkatesulu G.",
      "judgeName": "J. Padma Rao",
      "ppObjection": "Recovery complete; low risk",
      "defenceArgument": "Community roots; prior compliance",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "GRANTED",
      "aiRiskScore0100": "15",
      "systemRecommendation": "ACCEPT",
      "adjudication": "GRANTED â€“ WEEKLY REPORTING"
    },
    {
      "caseNo": "BMS/2026/0050",
      "firNo": "FIR/220/2026-RJM",
      "courtName": "Magistrate Court 2",
      "district": "East Godavari",
      "psIoName": "SI Ramana",
      "arrestDate": "2026-05-01",
      "filingDate": "2026-05-12",
      "hearingDate": "2026-06-10",
      "hearingTime": "12:00",
      "bailType": "First Bail",
      "ipcBnsSections": "IPC 323, 324",
      "offenceCategory": "Assault / Hurt",
      "proposedBailAmtRs": "30000",
      "accusedName": "V. Venkatesam",
      "judgeName": "J. Sita Devi",
      "ppObjection": "Identity mismatch flagged",
      "defenceArgument": "Trivial dispute; bail appropriate",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "ALERT",
      "aiRiskScore0100": "70",
      "systemRecommendation": "REVIEW",
      "adjudication": "IDENTITY ALERT â€“ BIOMETRIC MISMATCH"
    },
    {
      "caseNo": "BMS/2026/0055",
      "firNo": "FIR/310/2026-RJM",
      "courtName": "Sessions Court Room 1",
      "district": "East Godavari",
      "psIoName": "SI Mallik",
      "arrestDate": "2026-05-05",
      "filingDate": "2026-05-16",
      "hearingDate": "2026-06-12",
      "hearingTime": "11:30",
      "bailType": "First Bail",
      "ipcBnsSections": "IPC 420, 467",
      "offenceCategory": "Forgery / Fraud",
      "proposedBailAmtRs": "85000",
      "accusedName": "Suresh Babu T.",
      "judgeName": "J. Kameswara Rao",
      "ppObjection": "Forged title deed submitted",
      "defenceArgument": "Accused claims ignorance",
      "previousBailRejected": "No",
      "previousRejectionDate": "â€“",
      "rejectionReason": "â€“",
      "applicationStatus": "ALERT",
      "aiRiskScore0100": "90",
      "systemRecommendation": "REJECT",
      "adjudication": "DENIED â€“ FAKE DOCUMENT"
    }
  ],
  "accusedPersons": [
    {
      "caseNo": "BMS/2026/0042",
      "fullName": "Srinivas Rao Vemuri",
      "fathersName": "Venkateswara Rao",
      "dob": "1985-06-15",
      "age": "40",
      "aadhaarNo": "5678 2341 9012",
      "panNo": "ABCPV1234D",
      "mobile": "9849001122",
      "dlNo": "AP09-2011-1234567",
      "passportNo": "NIL",
      "employment": "Textile Trader",
      "monthlyIncomeRs": "45000",
      "bankAccNo": "SB/4421/ANDBANK",
      "cibilScore": "687.0",
      "residentialAddress": "W/8 Subhash Road, Rajamundry",
      "previousNcrbCases": "0",
      "bailComplianceHistory": "1/1 Bails Honoured",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "BMS/2026/0040",
      "fullName": "Anita Rao",
      "fathersName": "Krishnamurti Rao",
      "dob": "1992-03-22",
      "age": "34",
      "aadhaarNo": "6789 3452 0123",
      "panNo": "BCDQA5678E",
      "mobile": "9848112233",
      "dlNo": "NIL",
      "passportNo": "NIL",
      "employment": "Housewife",
      "monthlyIncomeRs": "0",
      "bankAccNo": "SB/8812/SBIRAJM",
      "cibilScore": "",
      "residentialAddress": "Flat 5B, RK Towers, Rajamundry",
      "previousNcrbCases": "2",
      "bailComplianceHistory": "",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "BMS/2026/0043",
      "fullName": "Priya Nair",
      "fathersName": "Suresh Nair",
      "dob": "1990-09-10",
      "age": "35",
      "aadhaarNo": "7890 4563 1234",
      "panNo": "CDEPN6789F",
      "mobile": "9848223344",
      "dlNo": "KL01-2014-9876543",
      "passportNo": "X4521879",
      "employment": "Software Engineer",
      "monthlyIncomeRs": "85000",
      "bankAccNo": "CB/3321/ICICI",
      "cibilScore": "742.0",
      "residentialAddress": "Nair House, Madanapalle",
      "previousNcrbCases": "0",
      "bailComplianceHistory": "",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "BMS/2026/0044",
      "fullName": "Ramesh Yadav",
      "fathersName": "Mohan Yadav",
      "dob": "1978-12-01",
      "age": "47",
      "aadhaarNo": "8901 5674 2345",
      "panNo": "DEFQR7890G",
      "mobile": "9849334455",
      "dlNo": "TS10-2009-8765432",
      "passportNo": "NIL",
      "employment": "Autorickshaw Driver",
      "monthlyIncomeRs": "18000",
      "bankAccNo": "SB/5534/ANDBANK",
      "cibilScore": "512.0",
      "residentialAddress": "Yadav Nagar, Rajamundry",
      "previousNcrbCases": "1",
      "bailComplianceHistory": "1/2 Bails Honoured",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "BMS/2026/0045",
      "fullName": "Kavya Sharma",
      "fathersName": "Rajendra Sharma",
      "dob": "1995-07-25",
      "age": "30",
      "aadhaarNo": "9012 6785 3456",
      "panNo": "EFGRS8901H",
      "mobile": "9849445566",
      "dlNo": "NIL",
      "passportNo": "Z7832154",
      "employment": "Student",
      "monthlyIncomeRs": "0",
      "bankAccNo": "JA/1190/SBIRAJM",
      "cibilScore": "",
      "residentialAddress": "Sharma Bhavan, Narsapur",
      "previousNcrbCases": "0",
      "bailComplianceHistory": "",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "BMS/2026/0046",
      "fullName": "Srinivas Reddy",
      "fathersName": "Venkataramana Reddy",
      "dob": "1982-02-14",
      "age": "44",
      "aadhaarNo": "0123 7896 4567",
      "panNo": "FGHST9012I",
      "mobile": "9848556677",
      "dlNo": "AP39-2006-4567890",
      "passportNo": "NIL",
      "employment": "Govt. Contractor",
      "monthlyIncomeRs": "62000",
      "bankAccNo": "CB/7723/HDFC",
      "cibilScore": "680.0",
      "residentialAddress": "Reddy Colony, Rajamundry",
      "previousNcrbCases": "1",
      "bailComplianceHistory": "1/1 Bails Honoured",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "BMS/2026/0047",
      "fullName": "Vijay Santi",
      "fathersName": "Raju Santi",
      "dob": "1975-11-30",
      "age": "50",
      "aadhaarNo": "1234 8907 5678",
      "panNo": "GHITU0123J",
      "mobile": "9847667788",
      "dlNo": "AP29-1999-3456789",
      "passportNo": "B7219034",
      "employment": "Land Owner",
      "monthlyIncomeRs": "90000",
      "bankAccNo": "SB/8841/ANDBANK",
      "cibilScore": "518.0",
      "residentialAddress": "Santi Estates, Kakinada",
      "previousNcrbCases": "3",
      "bailComplianceHistory": "0/2 Bails Honoured",
      "abscondingIncidents": "1",
      "immigrationLocStatus": "LOC ACTIVE â€“ WATCHLIST",
      "biometricStatus": "MISMATCH",
      "identityVerified": "UNDER REVIEW"
    },
    {
      "caseNo": "BMS/2026/0048",
      "fullName": "Krishnam Raju",
      "fathersName": "Seetharama Raju",
      "dob": "1965-01-12",
      "age": "61",
      "aadhaarNo": "5678 2341 9012",
      "panNo": "KLMXY4567N",
      "mobile": "9846001122",
      "dlNo": "AP09-1988-9876543",
      "passportNo": "P4512987",
      "employment": "Businessman",
      "monthlyIncomeRs": "120000",
      "bankAccNo": "CB/9934/HDFC",
      "cibilScore": "720.0",
      "residentialAddress": "Raju Mansion, Rajamundry",
      "previousNcrbCases": "3",
      "bailComplianceHistory": "1/3 Bails Honoured",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "BMS/2026/0065",
      "fullName": "Ravi Teja Kommuri",
      "fathersName": "Subba Rao Kommuri",
      "dob": "1999-04-05",
      "age": "27",
      "aadhaarNo": "2345 9018 6789",
      "panNo": "HIJUV1234K",
      "mobile": "9849778899",
      "dlNo": "TS07-2019-2345678",
      "passportNo": "NIL",
      "employment": "BBA Student",
      "monthlyIncomeRs": "0",
      "bankAccNo": "SB/2215/ANDBANK",
      "cibilScore": "",
      "residentialAddress": "Kommuri Nivas, Rajamundry",
      "previousNcrbCases": "0",
      "bailComplianceHistory": "",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "AWAITING",
      "identityVerified": "PENDING"
    },
    {
      "caseNo": "SC/98/2025",
      "fullName": "R. K. Naidu",
      "fathersName": "Ranga Rao Naidu",
      "dob": "1970-08-19",
      "age": "55",
      "aadhaarNo": "3456 0129 7890",
      "panNo": "IJKVW2345L",
      "mobile": "9846889900",
      "dlNo": "AP09-1993-1234567",
      "passportNo": "NIL",
      "employment": "Retired Clerk",
      "monthlyIncomeRs": "22000",
      "bankAccNo": "SB/6612/SBI",
      "cibilScore": "488.0",
      "residentialAddress": "Naidu Street, Rajamundry",
      "previousNcrbCases": "3",
      "bailComplianceHistory": "0/2 Bails Honoured",
      "abscondingIncidents": "1",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "SC/142/2024",
      "fullName": "Venkatesulu G.",
      "fathersName": "Gopala Rao G.",
      "dob": "1988-03-30",
      "age": "38",
      "aadhaarNo": "4567 1230 8901",
      "panNo": "JKLWX3456M",
      "mobile": "9848990011",
      "dlNo": "AP39-2008-0987654",
      "passportNo": "NIL",
      "employment": "Shop Owner",
      "monthlyIncomeRs": "38000",
      "bankAccNo": "SB/4490/ANDBANK",
      "cibilScore": "650.0",
      "residentialAddress": "Gopala Nivas, Rajamundry",
      "previousNcrbCases": "0",
      "bailComplianceHistory": "1/1 Bails Honoured",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    },
    {
      "caseNo": "BMS/2026/0050",
      "fullName": "V. Venkatesam",
      "fathersName": "Ramu Venkatesam",
      "dob": "1983-07-11",
      "age": "42",
      "aadhaarNo": "8923 4512 7801",
      "panNo": "VVRKM8923P",
      "mobile": "9848221100",
      "dlNo": "AP09-2007-7654321",
      "passportNo": "NIL",
      "employment": "Daily Wage Labour",
      "monthlyIncomeRs": "12000",
      "bankAccNo": "SB/1102/ANDBANK",
      "cibilScore": "390.0",
      "residentialAddress": "Venkatesam Nivas, Rajamundry",
      "previousNcrbCases": "0",
      "bailComplianceHistory": "",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "MISMATCH",
      "identityVerified": "ALERT â€“ IRIS MISMATCH"
    },
    {
      "caseNo": "BMS/2026/0055",
      "fullName": "Suresh Babu T.",
      "fathersName": "Tirupataiah T.",
      "dob": "1980-05-20",
      "age": "46",
      "aadhaarNo": "9034 5623 1122",
      "panNo": "SBTTT9034Q",
      "mobile": "9849112244",
      "dlNo": "AP29-2004-5544332",
      "passportNo": "NIL",
      "employment": "Real Estate Agent",
      "monthlyIncomeRs": "78000",
      "bankAccNo": "CB/4432/HDFC",
      "cibilScore": "560.0",
      "residentialAddress": "Tirupataiah Nivas, Rajamundry",
      "previousNcrbCases": "0",
      "bailComplianceHistory": "",
      "abscondingIncidents": "0",
      "immigrationLocStatus": "CLEAR",
      "biometricStatus": "VERIFIED",
      "identityVerified": "YES"
    }
  ],
  "suretyDetails": [
    {
      "caseNo": "BMS/2026/0042",
      "suretyName": "Madhava Rao Vemuri",
      "relationship": "Brother",
      "aadhaarNo": "6677 2341 8923",
      "panNo": "PVAMV1234Z",
      "mobile": "9849001222",
      "suretyType": "Property",
      "employment": "Retired Govt. Clerk",
      "monthlyIncomeRs": "35000",
      "avgAnnualItrRs": "420000",
      "propertyAddress": "W/8 Subhash Road, Rajamundry",
      "surveyNo": "RS-104/12-C",
      "pattaKhataNo": "P-8472-RJM",
      "marketValueRs": "650000",
      "titleDeedId": "TD-2026-RJM-482",
      "encumbranceStatus": "CLEAN â€“ UNENCUMBERED",
      "activeGuaranteesCount": "1",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "ADEQUATE",
      "disqualificationFlags": "NIL",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "ELIGIBLE"
    },
    {
      "caseNo": "BMS/2026/0040",
      "suretyName": "Srikanth Rao",
      "relationship": "Husband",
      "aadhaarNo": "7788 3452 9034",
      "panNo": "QWBSA5678Y",
      "mobile": "9848112200",
      "suretyType": "Individual",
      "employment": "Bank Manager",
      "monthlyIncomeRs": "72000",
      "avgAnnualItrRs": "864000",
      "propertyAddress": "",
      "surveyNo": "",
      "pattaKhataNo": "",
      "marketValueRs": "0",
      "titleDeedId": "",
      "encumbranceStatus": "",
      "activeGuaranteesCount": "0",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "ADEQUATE",
      "disqualificationFlags": "NIL",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "ELIGIBLE"
    },
    {
      "caseNo": "BMS/2026/0043",
      "suretyName": "Suresh Nair",
      "relationship": "Father",
      "aadhaarNo": "8899 4563 0145",
      "panNo": "RXCPN6789X",
      "mobile": "9848223311",
      "suretyType": "Individual",
      "employment": "Retired Teacher",
      "monthlyIncomeRs": "28000",
      "avgAnnualItrRs": "336000",
      "propertyAddress": "",
      "surveyNo": "",
      "pattaKhataNo": "",
      "marketValueRs": "0",
      "titleDeedId": "",
      "encumbranceStatus": "",
      "activeGuaranteesCount": "1",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "BORDERLINE",
      "disqualificationFlags": "NIL",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "CONDITIONAL"
    },
    {
      "caseNo": "BMS/2026/0044",
      "suretyName": "Laxmi Yadav",
      "relationship": "Wife",
      "aadhaarNo": "9900 5674 1256",
      "panNo": "SYDQR7890W",
      "mobile": "9849334422",
      "suretyType": "Property",
      "employment": "Housewife",
      "monthlyIncomeRs": "0",
      "avgAnnualItrRs": "0",
      "propertyAddress": "Yadav Street, Rajamundry",
      "surveyNo": "RS-221/4-B",
      "pattaKhataNo": "P-1122-RJM",
      "marketValueRs": "320000",
      "titleDeedId": "TD-2026-RJM-220",
      "encumbranceStatus": "CLEAN â€“ UNENCUMBERED",
      "activeGuaranteesCount": "0",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "BORDERLINE",
      "disqualificationFlags": "Surety previously overloaded",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "CONDITIONAL"
    },
    {
      "caseNo": "BMS/2026/0045",
      "suretyName": "Ravi Sharma",
      "relationship": "Uncle",
      "aadhaarNo": "0011 6785 2367",
      "panNo": "TZERS8901V",
      "mobile": "9848556600",
      "suretyType": "Individual",
      "employment": "Engineer",
      "monthlyIncomeRs": "95000",
      "avgAnnualItrRs": "1140000",
      "propertyAddress": "",
      "surveyNo": "",
      "pattaKhataNo": "",
      "marketValueRs": "0",
      "titleDeedId": "",
      "encumbranceStatus": "",
      "activeGuaranteesCount": "0",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "ADEQUATE",
      "disqualificationFlags": "NIL",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "ELIGIBLE"
    },
    {
      "caseNo": "BMS/2026/0046",
      "suretyName": "Sarada Reddy",
      "relationship": "Mother",
      "aadhaarNo": "1122 7896 3478",
      "panNo": "UAFST9012U",
      "mobile": "9848556600",
      "suretyType": "Individual",
      "employment": "Retired",
      "monthlyIncomeRs": "18000",
      "avgAnnualItrRs": "216000",
      "propertyAddress": "",
      "surveyNo": "",
      "pattaKhataNo": "",
      "marketValueRs": "0",
      "titleDeedId": "",
      "encumbranceStatus": "",
      "activeGuaranteesCount": "1",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "BORDERLINE",
      "disqualificationFlags": "NIL",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "CONDITIONAL"
    },
    {
      "caseNo": "BMS/2026/0047",
      "suretyName": "Mani Santi",
      "relationship": "Brother",
      "aadhaarNo": "2233 8907 4589",
      "panNo": "VBGTU0123T",
      "mobile": "9847667711",
      "suretyType": "Property",
      "employment": "Farmer",
      "monthlyIncomeRs": "25000",
      "avgAnnualItrRs": "300000",
      "propertyAddress": "Santi Plot, Kakinada",
      "surveyNo": "RS-241/8-A",
      "pattaKhataNo": "P-9921-KAK",
      "marketValueRs": "90000",
      "titleDeedId": "TD-2025-KAK-109",
      "encumbranceStatus": "AWAITING MUTATION",
      "activeGuaranteesCount": "3",
      "maxAllowed": "2",
      "guaranteeOverload": "YES",
      "financialCapacityCheck": "INADEQUATE",
      "disqualificationFlags": "3 active guarantees; property mutation pending",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "DISQUALIFIED"
    },
    {
      "caseNo": "BMS/2026/0048",
      "suretyName": "Krishnam Raju (Sr.)",
      "relationship": "Father",
      "aadhaarNo": "3344 9018 5690",
      "panNo": "XDJKW2345R",
      "mobile": "9846001111",
      "suretyType": "Property",
      "employment": "Retired Revenue Inspector",
      "monthlyIncomeRs": "42000",
      "avgAnnualItrRs": "3633333",
      "propertyAddress": "Raju Plot, Rajamundry",
      "surveyNo": "RS-301/3-A",
      "pattaKhataNo": "P-0034-RJM",
      "marketValueRs": "1200000",
      "titleDeedId": "TD-2026-RJM-991",
      "encumbranceStatus": "CLEAN â€“ UNENCUMBERED",
      "activeGuaranteesCount": "3",
      "maxAllowed": "2",
      "guaranteeOverload": "YES",
      "financialCapacityCheck": "ADEQUATE",
      "disqualificationFlags": "3 active guarantees (limit exceeded)",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "DISQUALIFIED"
    },
    {
      "caseNo": "BMS/2026/0065",
      "suretyName": "Subba Rao Kommuri",
      "relationship": "Father",
      "aadhaarNo": "4455 0129 6701",
      "panNo": "YEKLX3456Q",
      "mobile": "9849778800",
      "suretyType": "Individual",
      "employment": "School Teacher",
      "monthlyIncomeRs": "40000",
      "avgAnnualItrRs": "480000",
      "propertyAddress": "",
      "surveyNo": "",
      "pattaKhataNo": "",
      "marketValueRs": "0",
      "titleDeedId": "",
      "encumbranceStatus": "",
      "activeGuaranteesCount": "0",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "ADEQUATE",
      "disqualificationFlags": "NIL",
      "biometricStatus": "AWAITING",
      "suretyVerdict": "PENDING"
    },
    {
      "caseNo": "SC/98/2025",
      "suretyName": "Kanakaiah Naidu",
      "relationship": "Son",
      "aadhaarNo": "5566 1230 7812",
      "panNo": "ZFLMY4567P",
      "mobile": "9848112200",
      "suretyType": "Individual",
      "employment": "Govt. Employee",
      "monthlyIncomeRs": "48000",
      "avgAnnualItrRs": "576000",
      "propertyAddress": "",
      "surveyNo": "",
      "pattaKhataNo": "",
      "marketValueRs": "0",
      "titleDeedId": "",
      "encumbranceStatus": "",
      "activeGuaranteesCount": "2",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "BORDERLINE",
      "disqualificationFlags": "Prior bail default on SC/55/2022",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "DISQUALIFIED"
    },
    {
      "caseNo": "SC/142/2024",
      "suretyName": "Padmaja G.",
      "relationship": "Wife",
      "aadhaarNo": "6677 2341 8923",
      "panNo": "WCHIV1234S",
      "mobile": "9848990022",
      "suretyType": "Individual",
      "employment": "Nurse",
      "monthlyIncomeRs": "32000",
      "avgAnnualItrRs": "384000",
      "propertyAddress": "",
      "surveyNo": "",
      "pattaKhataNo": "",
      "marketValueRs": "0",
      "titleDeedId": "",
      "encumbranceStatus": "",
      "activeGuaranteesCount": "0",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "ADEQUATE",
      "disqualificationFlags": "NIL",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "ELIGIBLE"
    },
    {
      "caseNo": "BMS/2026/0055",
      "suretyName": "Tirupataiah T.",
      "relationship": "Father",
      "aadhaarNo": "7788 3452 9034",
      "panNo": "TTTMS7788R",
      "mobile": "9849112200",
      "suretyType": "Property",
      "employment": "Retired",
      "monthlyIncomeRs": "22000",
      "avgAnnualItrRs": "264000",
      "propertyAddress": "TP Nivas, Rajamundry",
      "surveyNo": "RS-199/6-B",
      "pattaKhataNo": "P-5511-RJM",
      "marketValueRs": "500000",
      "titleDeedId": "TD-2026-RJM-007",
      "encumbranceStatus": "CLEAN â€“ UNENCUMBERED",
      "activeGuaranteesCount": "1",
      "maxAllowed": "2",
      "guaranteeOverload": "NO",
      "financialCapacityCheck": "ADEQUATE",
      "disqualificationFlags": "Title Deed mismatch flagged by Registration API",
      "biometricStatus": "VERIFIED",
      "suretyVerdict": "DISQUALIFIED â€“ FAKE DEED"
    }
  ],
  "propertyCrossLinking": [
    {
      "surveyNo": "RS-104/12-C",
      "propertyAddress": "W/8 Subhash Road, Rajamundry",
      "registeredOwner": "Madhava Rao Vemuri",
      "titleDeedId": "TD-2026-RJM-482",
      "marketValueRs": "650000",
      "encumbranceStatus": "MUTATED â€“ COURT LIEN",
      "mutationEntryRecorded": "YES",
      "pledge1CaseNo": "BMS/2026/0042",
      "pledge1Surety": "Madhava Rao Vemuri",
      "pledge1Court": "Sessions Court 2",
      "pledge2CaseNo": "â€“",
      "pledge2Surety": "â€“",
      "pledge2Court": "â€“",
      "duplicatePledgeAlert": "NO",
      "crosscourtFlag": "NO",
      "systemAction": "Encumbrance Locked â€“ No Sale Permitted"
    },
    {
      "surveyNo": "RS-104/12",
      "propertyAddress": "Subhash Road, Rajamundry",
      "registeredOwner": "Ravi Kumar P.",
      "titleDeedId": "TD-2026-RJM-111",
      "marketValueRs": "480000",
      "encumbranceStatus": "ENCUMBERED",
      "mutationEntryRecorded": "YES",
      "pledge1CaseNo": "SC-101/2026",
      "pledge1Surety": "Ravi Kumar P.",
      "pledge1Court": "Sub-Court 1",
      "pledge2CaseNo": "SC-88/2026",
      "pledge2Surety": "Ravi Kumar P.",
      "pledge2Court": "Sessions Court 2",
      "duplicatePledgeAlert": "YES â€“ CRITICAL FRAUD",
      "crosscourtFlag": "YES â€“ CROSS COURT",
      "systemAction": "Block Surety Triggered â€“ FRD/2026/001"
    },
    {
      "surveyNo": "RS-241/8-A",
      "propertyAddress": "Santi Plot, Kakinada",
      "registeredOwner": "Mani Santi",
      "titleDeedId": "TD-2025-KAK-109",
      "marketValueRs": "90000",
      "encumbranceStatus": "AWAITING MUTATION",
      "mutationEntryRecorded": "NO",
      "pledge1CaseNo": "BMS/2026/0047",
      "pledge1Surety": "Mani Santi",
      "pledge1Court": "Sessions Court 2",
      "pledge2CaseNo": "â€“",
      "pledge2Surety": "â€“",
      "pledge2Court": "â€“",
      "duplicatePledgeAlert": "NO",
      "crosscourtFlag": "NO",
      "systemAction": "Mutation Pending â€“ Property Operationally Inactive"
    },
    {
      "surveyNo": "RS-301/3-A",
      "propertyAddress": "Raju Plot, Rajamundry",
      "registeredOwner": "Krishnam Raju (Sr.)",
      "titleDeedId": "TD-2026-RJM-991",
      "marketValueRs": "1200000",
      "encumbranceStatus": "CLEAN",
      "mutationEntryRecorded": "NO",
      "pledge1CaseNo": "BMS/2026/0048",
      "pledge1Surety": "Krishnam Raju (Sr.)",
      "pledge1Court": "Sessions Court 2",
      "pledge2CaseNo": "â€“",
      "pledge2Surety": "â€“",
      "pledge2Court": "â€“",
      "duplicatePledgeAlert": "NO",
      "crosscourtFlag": "NO",
      "systemAction": "Surety Disqualified (Guarantee Overload) â€“ Property not pledged"
    },
    {
      "surveyNo": "RS-221/4-B",
      "propertyAddress": "Yadav Street, Rajamundry",
      "registeredOwner": "Laxmi Yadav",
      "titleDeedId": "TD-2026-RJM-220",
      "marketValueRs": "320000",
      "encumbranceStatus": "CLEAN â€“ UNENCUMBERED",
      "mutationEntryRecorded": "NO",
      "pledge1CaseNo": "BMS/2026/0044",
      "pledge1Surety": "Laxmi Yadav",
      "pledge1Court": "Magistrate Court 3",
      "pledge2CaseNo": "â€“",
      "pledge2Surety": "â€“",
      "pledge2Court": "â€“",
      "duplicatePledgeAlert": "NO",
      "crosscourtFlag": "NO",
      "systemAction": "Pending Mutation Entry"
    },
    {
      "surveyNo": "RS-199/6-B",
      "propertyAddress": "TP Nivas, Rajamundry",
      "registeredOwner": "Tirupataiah T.",
      "titleDeedId": "TD-2026-RJM-007",
      "marketValueRs": "500000",
      "encumbranceStatus": "CLEAN",
      "mutationEntryRecorded": "NO",
      "pledge1CaseNo": "BMS/2026/0055",
      "pledge1Surety": "Tirupataiah T.",
      "pledge1Court": "Sessions Court 1",
      "pledge2CaseNo": "â€“",
      "pledge2Surety": "â€“",
      "pledge2Court": "â€“",
      "duplicatePledgeAlert": "NO",
      "crosscourtFlag": "NO",
      "systemAction": "Title Deed Mismatch â€“ Flagged for Revenue Dept Verification"
    }
  ],
  "biometricIdentity": [
    {
      "caseNo": "BMS/2026/0042",
      "person": "Srinivas Rao Vemuri",
      "role": "Accused",
      "aadhaarNo": "5678 2341 9012",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "99.8",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "0 Matches",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-05-01 09:10",
      "counterOfficer": "Court Officer Ramaiah"
    },
    {
      "caseNo": "BMS/2026/0042",
      "person": "Madhava Rao Vemuri",
      "role": "Surety",
      "aadhaarNo": "6677 2341 8923",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "99.5",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "0 Matches",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-05-01 09:25",
      "counterOfficer": "Court Officer Ramaiah"
    },
    {
      "caseNo": "BMS/2026/0040",
      "person": "Anita Rao",
      "role": "Accused",
      "aadhaarNo": "6789 3452 0123",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "99.1",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "2 FIRs",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-04-20 10:00",
      "counterOfficer": "Court Officer Lakshmi"
    },
    {
      "caseNo": "BMS/2026/0043",
      "person": "Priya Nair",
      "role": "Accused",
      "aadhaarNo": "7890 4563 1234",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "98.7",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "YES",
      "electionIdVerified": "YES",
      "ncrbMatch": "0 Matches",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-05-03 09:30",
      "counterOfficer": "Court Officer Ramaiah"
    },
    {
      "caseNo": "BMS/2026/0044",
      "person": "Ramesh Yadav",
      "role": "Accused",
      "aadhaarNo": "8901 5674 2345",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "97.2",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "1 FIR",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-05-05 09:15",
      "counterOfficer": "Court Officer Suresh"
    },
    {
      "caseNo": "BMS/2026/0045",
      "person": "Kavya Sharma",
      "role": "Accused",
      "aadhaarNo": "9012 6785 3456",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "99.0",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "",
      "passportVerified": "YES",
      "electionIdVerified": "YES",
      "ncrbMatch": "0 Matches",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-05-07 09:00",
      "counterOfficer": "Court Officer Lakshmi"
    },
    {
      "caseNo": "BMS/2026/0046",
      "person": "Srinivas Reddy",
      "role": "Accused",
      "aadhaarNo": "0123 7896 4567",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "98.3",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "1 FIR",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-05-09 09:20",
      "counterOfficer": "Court Officer Ramaiah"
    },
    {
      "caseNo": "BMS/2026/0047",
      "person": "Vijay Santi",
      "role": "Accused",
      "aadhaarNo": "1234 8907 5678",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "96.1",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "YES",
      "electionIdVerified": "YES",
      "ncrbMatch": "3 FIRs",
      "locImmigrationStatus": "LOC ACTIVE â€“ WATCHLIST",
      "identityFinalStatus": "ALERT â€“ LOC FLAG",
      "verifiedOn": "2026-05-11 14:00",
      "counterOfficer": "Court Officer Suresh"
    },
    {
      "caseNo": "BMS/2026/0048",
      "person": "Krishnam Raju",
      "role": "Accused",
      "aadhaarNo": "5678 2341 9012",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "98.9",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "YES",
      "electionIdVerified": "YES",
      "ncrbMatch": "3 FIRs",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-05-13 09:05",
      "counterOfficer": "Court Officer Ramaiah"
    },
    {
      "caseNo": "BMS/2026/0050",
      "person": "V. Venkatesam",
      "role": "Accused",
      "aadhaarNo": "8923 4512 7801",
      "fingerprintScan10": "8/10",
      "irisScan2": "1/2",
      "biometricMatch": "61.3",
      "aadhaarApiResult": "MISMATCH â€“ IRIS FAIL",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "0 Matches",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "ALERT â€“ BIOMETRIC MISMATCH",
      "verifiedOn": "2026-05-12 11:40",
      "counterOfficer": "Court Officer Lakshmi"
    },
    {
      "caseNo": "BMS/2026/0065",
      "person": "Ravi Teja Kommuri",
      "role": "Accused",
      "aadhaarNo": "2345 9018 6789",
      "fingerprintScan10": "AWAITING",
      "irisScan2": "AWAITING",
      "biometricMatch": "",
      "aadhaarApiResult": "PENDING",
      "panVerified": "PENDING",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "0 Matches",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "AWAITING",
      "verifiedOn": "2026-05-20",
      "counterOfficer": "Counter Not Yet Executed"
    },
    {
      "caseNo": "SC/98/2025",
      "person": "R. K. Naidu",
      "role": "Accused",
      "aadhaarNo": "3456 0129 7890",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "97.8",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "3 FIRs + Abscond",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2025-11-20 10:00",
      "counterOfficer": "Court Officer Suresh"
    },
    {
      "caseNo": "SC/142/2024",
      "person": "Venkatesulu G.",
      "role": "Accused",
      "aadhaarNo": "4567 1230 8901",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "98.5",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "0 Matches",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2024-08-15 09:30",
      "counterOfficer": "Court Officer Devi"
    },
    {
      "caseNo": "BMS/2026/0055",
      "person": "Suresh Babu T.",
      "role": "Accused",
      "aadhaarNo": "9034 5623 1122",
      "fingerprintScan10": "10/10",
      "irisScan2": "2/2",
      "biometricMatch": "99.2",
      "aadhaarApiResult": "CONFIRMED",
      "panVerified": "YES",
      "dlVerified": "YES",
      "passportVerified": "",
      "electionIdVerified": "YES",
      "ncrbMatch": "0 Matches",
      "locImmigrationStatus": "CLEAR",
      "identityFinalStatus": "VERIFIED",
      "verifiedOn": "2026-05-16 10:00",
      "counterOfficer": "Court Officer Ramaiah"
    }
  ],
  "fraudAlerts": [
    {
      "alertId": "FRD/2026/001",
      "alertType": "Duplicate Property Pledge",
      "severity": "CRITICAL",
      "caseNos": "SC-101/2026; SC-88/2026",
      "accusedSurety": "Ravi Kumar P.",
      "aadhaarPropertyRef": "Survey RS-104/12",
      "description": "Same property pledged in Sub-Court 1 AND Sessions Court simultaneously",
      "detectedOn": "2026-05-18",
      "detectingModule": "Property Cross-Link Engine",
      "actionTaken": "Block Surety â€“ Encumbrance Frozen",
      "investigatingOfficer": "SI Mallik",
      "alertStatus": "OPEN"
    },
    {
      "alertId": "FRD/2026/002",
      "alertType": "Biometric Identity Mismatch",
      "severity": "CRITICAL",
      "caseNos": "BMS/2026/0050",
      "accusedSurety": "V. Venkatesam",
      "aadhaarPropertyRef": "Aadhaar 8923 4512 7801",
      "description": "Live iris scan failed to match UIDAI Aadhaar database (8/10 fingers, 1/2 iris)",
      "detectedOn": "2026-05-19",
      "detectingModule": "Biometric Verification Module",
      "actionTaken": "Remand Proxy Initiated â€“ Case Suspended",
      "investigatingOfficer": "SI Ramana",
      "alertStatus": "OPEN"
    },
    {
      "alertId": "FRD/2026/003",
      "alertType": "Surety Guarantee Overload",
      "severity": "OVERCOMMIT",
      "caseNos": "Multiple",
      "accusedSurety": "K.N. Murthy",
      "aadhaarPropertyRef": "PAN KNMKM1234Z",
      "description": "3 active bail guarantees active across multiple regional divisions (limit: 2)",
      "detectedOn": "2026-05-20",
      "detectingModule": "Surety Capacity Engine",
      "actionTaken": "View Obligations Flagged â€“ Surety Disqualified",
      "investigatingOfficer": "SI Annapurna",
      "alertStatus": "UNDER REVIEW"
    },
    {
      "alertId": "FRD/2026/004",
      "alertType": "Fake / Forged Title Deed",
      "severity": "CRITICAL",
      "caseNos": "BMS/2026/0055",
      "accusedSurety": "Suresh Babu T.",
      "aadhaarPropertyRef": "TD-2026-RJM-009",
      "description": "Title deed reference does not match Registration & Stamps Dept API",
      "detectedOn": "2026-05-21",
      "detectingModule": "Document Auth Module",
      "actionTaken": "Document Hold â€“ Case Alert Sent to Judge",
      "investigatingOfficer": "SI Mallik",
      "alertStatus": "OPEN"
    },
    {
      "alertId": "FRD/2026/005",
      "alertType": "Flight Risk / LOC Active",
      "severity": "ALERT",
      "caseNos": "BMS/2026/0047",
      "accusedSurety": "Vijay Santi",
      "aadhaarPropertyRef": "Passport B7219034",
      "description": "1 prior absconding incident â€“ Immigration LOC ACTIVE via MEA API",
      "detectedOn": "2026-05-22",
      "detectingModule": "Immigration Gateway",
      "actionTaken": "Priority Flag to Immigration + Judge",
      "investigatingOfficer": "SI Kishore",
      "alertStatus": "MONITORING"
    },
    {
      "alertId": "FRD/2026/006",
      "alertType": "Biometric Substitution Attempt",
      "severity": "CRITICAL",
      "caseNos": "BMS/2026/0058",
      "accusedSurety": "D. Raju",
      "aadhaarPropertyRef": "Aadhaar 7891 2340 6654",
      "description": "Third-party fingerprint attempted at biometric counter for accused",
      "detectedOn": "2026-05-23",
      "detectingModule": "Counter Biometric Engine",
      "actionTaken": "Case Suspended â€“ FIR Filed",
      "investigatingOfficer": "SI Suresh",
      "alertStatus": "OPEN"
    },
    {
      "alertId": "FRD/2026/007",
      "alertType": "Surety Prior Default",
      "severity": "WARNING",
      "caseNos": "SC/98/2025",
      "accusedSurety": "Kanakaiah Naidu",
      "aadhaarPropertyRef": "PAN ZFLMY4567P",
      "description": "Surety previously defaulted on bail obligation in SC/55/2022 Rajamundry",
      "detectedOn": "2026-05-10",
      "detectingModule": "Surety History Module",
      "actionTaken": "Disqualification Logged",
      "investigatingOfficer": "SI Suresh",
      "alertStatus": "CLOSED"
    },
    {
      "alertId": "FRD/2026/008",
      "alertType": "Suspended Advocate Appearing",
      "severity": "WARNING",
      "caseNos": "BMS/2026/0052",
      "accusedSurety": "Adv. P.R. Mohan",
      "aadhaarPropertyRef": "Bar Council ID: AP-ADV-0892",
      "description": "Bar Council API shows suspension â€“ advocate still appearing in court",
      "detectedOn": "2026-05-25",
      "detectingModule": "Bar Council Verification",
      "actionTaken": "Alert to Presiding Judge â€“ Proceeding Halted",
      "investigatingOfficer": "SI Ramana",
      "alertStatus": "OPEN"
    }
  ],
  "externalDBIntegrations": [
    {
      "integrationCategory": "Govt. Identity",
      "systemApiName": "UIDAI Aadhaar API",
      "govPortal": "uidai.gov.in",
      "encryption": "AES-256 / SSL",
      "caseNoSample": "BMS/2026/0042",
      "queryPerformed": "Biometric + Identity Match",
      "resultReturned": "Identity FULLY CONFIRMED â€“ 10 fingers + Dual Iris",
      "latencyMs": "245",
      "lastChecked": "2026-05-29 09:00",
      "apiStatus": "CONNECTED"
    },
      {
        "integrationCategory": "Financial Profile",
        "systemApiName": "Income Tax ITR API",
        "govPortal": "incometax.gov.in",
        "encryption": "AES-256 / SSL",
        "caseNoSample": "BMS/2026/0042",
        "queryPerformed": "ITR Income Verification",
        "resultReturned": "ITR Verified - Annual Income Rs 4,50,000",
        "latencyMs": "195",
        "lastChecked": "2026-05-29 09:15",
        "apiStatus": "CONNECTED"
      },
      {
        "integrationCategory": "Credit & NPA",
        "systemApiName": "RBI Credit Bureau API",
        "govPortal": "rbi.org.in",
        "encryption": "SSL / TLS",
        "caseNoSample": "BMS/2026/0042",
        "queryPerformed": "CIBIL Score + NPA Check",
        "resultReturned": "CIBIL: 687.0 - Active NPA: NONE",
        "latencyMs": "180",
        "lastChecked": "2026-05-29 09:20",
        "apiStatus": "CONNECTED"
      },
      {
        "integrationCategory": "Crime Records",
        "systemApiName": "NCRB CCTNS API",
        "govPortal": "ncrb.gov.in",
        "encryption": "AES-256 / VPN",
        "caseNoSample": "BMS/2026/0042",
        "queryPerformed": "National Criminal History Check",
        "resultReturned": "0 Matches Found in CCTNS Database",
        "latencyMs": "320",
        "lastChecked": "2026-05-29 09:10",
        "apiStatus": "CONNECTED"
      },
      {
        "integrationCategory": "Immigration Watch",
        "systemApiName": "MEA LOC API",
        "govPortal": "passportindia.gov.in",
        "encryption": "AES-256 / SSL",
        "caseNoSample": "BMS/2026/0047",
        "queryPerformed": "MEA Lookout Circular check",
        "resultReturned": "LOC ACTIVE - WATCHLIST SEARCH FOUND",
        "latencyMs": "290",
        "lastChecked": "2026-05-29 09:30",
        "apiStatus": "CONNECTED"
      },
      {
        "integrationCategory": "Land Records",
        "systemApiName": "Bhudar AP Revenue API",
        "govPortal": "meebhoomi.ap.gov.in",
        "encryption": "AES-256 / SSL",
        "caseNoSample": "BMS/2026/0042",
        "queryPerformed": "Title Deed Survey No Verification",
        "resultReturned": "Survey RS-104/12-C Verified. Owner: Madhava Rao Vemuri",
        "latencyMs": "410",
        "lastChecked": "2026-05-29 09:35",
        "apiStatus": "CONNECTED"
      }
    ]
};

// Helper functions for easy querying
export function getCaseByNo(caseNo) {
    return db.bailApplications.find(c => c.caseNo === caseNo);
}

export function getAccusedByCase(caseNo) {
    return db.accusedPersons.find(a => a.caseNo === caseNo);
}

export function getSuretyByCase(caseNo) {
    return db.suretyDetails.find(s => s.caseNo === caseNo);
}

export function getBiometricByCase(caseNo) {
    return db.biometricIdentity.find(b => b.caseNo === caseNo && b.role === 'Accused');
}

export function getComplianceByCase(caseNo) {
    const c = getCaseByNo(caseNo);
    const accused = getAccusedByCase(caseNo);
    if (!c) return [];
    
    return [
        {
            checkType: "Weekly Police Reporting",
            frequency: "Weekly",
            deliveryMethod: "Physical PS Visit",
            recipient: `${c.psIoName || 'SI Ravi Kumar'} (Rajamundry PS)`,
            status: c.applicationStatus === 'GRANTED' ? "ACTIVE" : "SCHEDULED",
            nextDue: "Every Monday, 10:00 AM"
        },
        {
            checkType: "Passport Surrender Check",
            frequency: "Continuous",
            deliveryMethod: "LOC Watchlist Link",
            recipient: "Bureau of Immigration / MEA",
            status: accused && accused.immigrationLocStatus !== 'CLEAR' ? "ACTIVE" : "AWAITING",
            nextDue: "Immediate on release"
        },
        {
            checkType: "Witness Non-Contact Order",
            frequency: "Continuous",
            deliveryMethod: "Legal Restriction",
            recipient: "AP Police Crimes Network",
            status: c.applicationStatus === 'GRANTED' ? "ACTIVE" : "SCHEDULED",
            nextDue: "Ongoing tracking"
        },
        {
            checkType: "Surety Property Mutation Audit",
            frequency: "Monthly",
            deliveryMethod: "Webland Revenue Link",
            recipient: "Webland Revenue Registry",
            status: c.applicationStatus === 'GRANTED' ? "ACTIVE" : "PENDING",
            nextDue: "Monthly verification"
        }
    ];
}

export function getOpenFraudAlerts() {
    return db.fraudAlerts.filter(a => a.alertStatus === 'OPEN' || a.alertStatus === 'UNDER REVIEW');
}

export function getCasesByStatus(status) {
    return db.bailApplications.filter(c => c.applicationStatus === status);
}

export function getHighRiskCases() {
    return db.bailApplications.filter(c => {
        const score = parseInt(c.aiRiskScore0100 || c.aiRiskScore010 || "0");
        return score >= 80;
    });
}

export function getFullCaseProfile(caseNo) {
    const application = getCaseByNo(caseNo);
    if (!application) return null;
    const accused = getAccusedByCase(caseNo);
    const surety = getSuretyByCase(caseNo);
    const biometrics = db.biometricIdentity.filter(b => b.caseNo === caseNo);
    const activeAlerts = db.fraudAlerts.filter(a => a.caseNos && a.caseNos.includes(caseNo));
    
    return {
        application,
        accused,
        surety,
        biometrics,
        activeAlerts
    };
}

